/** Shared wire types for Moonraker's JSON-RPC 2.0 API. */

export interface JsonRpcRequest {
  jsonrpc: "2.0";
  method: string;
  params?: object;
  id: number;
}

export interface JsonRpcError {
  code: number;
  message: string;
}

/** `printer.objects.list` — a flat list of object names, nothing more. */
export interface PrinterObjectsListResult {
  objects: string[];
}

/**
 * `printer.objects.subscribe` — the response carries a full snapshot of every
 * object in the requested set, so subscribing doubles as the initial query.
 */
export interface PrinterObjectsSubscribeResult {
  eventtime: number;
  status: Record<string, unknown>;
}

/**
 * `notify_status_update` params are **positional**: `[statusDiff, eventtime]`.
 * The diff contains only the fields that changed since the last push.
 */
export type NotifyStatusUpdateParams = [Record<string, unknown>, number];

/** Status values are deliberately untyped — Klipper object shapes vary wildly. */
export type StatusValue = unknown;

/** One line from Moonraker's ring-buffer gcode log (`server.gcode_store`). */
export interface GcodeStoreItem {
  message: string;
  time: number;
  type: "command" | "response";
}

export interface GcodeStoreResult {
  gcode_store: GcodeStoreItem[];
}

/**
 * `printer.objects.query {gcode: ['commands']}` — every registered command,
 * with a `help` field only for the subset Klipper gave a description to.
 * Deliberately used instead of `printer.gcode.help`, which silently *omits*
 * any command with no description at all — including core codes like G28,
 * G0/G1, G90/G91/G92, M112, M114, M117, and the SD-card M-commands, none of
 * which pass `desc=` when registering. This is the complete set; that isn't.
 */
export interface GcodeCommandsResult {
  commands: Record<string, { help?: string }>;
}

/** Client-side normalized form: every command name mapped to its help text
 *  (empty string when Klipper registered no description for it). */
export type GcodeHelpResult = Record<string, string>;

/**
 * `notify_gcode_response` params are **positional**: `[message]`. A single
 * notification's message may contain embedded `\n` for multi-line output.
 */
export type NotifyGcodeResponseParams = [string];

/**
 * One entry from the bundled Klipper built-in command reference
 * (`klipper-builtins.json`, generated by `scripts/generate_klipper_builtins.py`
 * from a local Klipper checkout's `docs/G-Codes.md`). Covers commands Klipper
 * itself ships — G28, RESPOND, SET_SERVO, etc. — none of which expose a
 * parameter schema through any live API. Re-run the script to refresh this
 * after updating Klipper; see the script's docstring for why it parses the
 * docs rather than the Python source.
 */
export interface BuiltinCommandInfo {
  syntax: string;
  description: string;
  params: { name: string; optional: boolean }[];
}

/**
 * `server.info` — the subset used to read Klipper's own connection state.
 * `klippy_state` is one of "ready" | "startup" | "shutdown" | "error" |
 * "disconnected"; kept as a bare string here since Moonraker treats it as
 * such and any future value should still pass through rather than vanish.
 */
export interface ServerInfoResult {
  klippy_connected: boolean;
  klippy_state: string;
}

/** One entry from `server.files.list {root: "logs"}` — result is a bare
 *  array (confirmed in file_manager.py's `_handle_filelist_request`), not
 *  wrapped in an object. */
export interface FileListItem {
  path: string;
  size: number;
  modified: number;
  permissions: string;
}

/**
 * `notify_filelist_changed` params are **positional**: `[info]`, one object
 * (confirmed in file_manager.py's `notify_filelist_changed`/`websockets.py`'s
 * notify_clients — `data` is wrapped in a tuple, so JSON params is a
 * single-element array). `item` is absent for a bare directory event in some
 * actions, hence optional.
 */
export interface FilelistChangedInfo {
  action: string;
  item?: {
    root: string;
    path: string;
    size: number;
    modified: number;
    permissions: string;
  };
  /** Present for move_file/move_dir: the path an item moved *from*. */
  source_item?: { root: string; path: string };
}
export type NotifyFilelistChangedParams = [FilelistChangedInfo];
